name: chitchat
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  audioplayers: ^5.2.1
  chewie: ^1.7.5
  cloud_firestore: ^4.15.4
  country_picker: ^2.0.24
  cupertino_icons: ^1.0.2
  easy_pdf_viewer: ^1.0.7
  file_picker: ^6.2.0
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.6
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.1.0
  flutter_pdfview: ^1.3.2
  flutter_sound: 9.2.13
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  http: ^1.2.0
  iconsax: ^0.0.8
  image_picker: ^1.0.7
  intl: ^0.19.0
  lottie: ^3.0.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  pinput: ^3.0.1
  provider: ^6.1.1
  record: ^5.0.4
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  video_player: ^2.8.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
