// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQfklzo3QocXC9MOWwNPze6fh0WzLn5Po',
    appId: '1:434760967247:web:9896017ced22b04755f63a',
    messagingSenderId: '434760967247',
    projectId: 'chatapp-6baa4',
    authDomain: 'chatapp-6baa4.firebaseapp.com',
    storageBucket: 'chatapp-6baa4.appspot.com',
    measurementId: 'G-J68E6HS604',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUubvZ_DveOrU4PMELVNFXKvkQCdHOw3o',
    appId: '1:434760967247:android:a9ac2a6d6157d6c055f63a',
    messagingSenderId: '434760967247',
    projectId: 'chatapp-6baa4',
    storageBucket: 'chatapp-6baa4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMzW7rJJxXnp1Z_8zwTYi5oX_3GveiPCM',
    appId: '1:434760967247:ios:774eb996f2c7606955f63a',
    messagingSenderId: '434760967247',
    projectId: 'chatapp-6baa4',
    storageBucket: 'chatapp-6baa4.appspot.com',
    iosBundleId: 'com.example.chitchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMzW7rJJxXnp1Z_8zwTYi5oX_3GveiPCM',
    appId: '1:434760967247:ios:b445ea9c62488caf55f63a',
    messagingSenderId: '434760967247',
    projectId: 'chatapp-6baa4',
    storageBucket: 'chatapp-6baa4.appspot.com',
    iosBundleId: 'com.example.chitchat.RunnerTests',
  );
}
